### PR TITLE
Adding a tool for dictionary lockout setup and reset

### PR DESCRIPTION
**Pull request by williamcroberts**
Signed-off-by: William Roberts <william.c.roberts@intel.com>

### CODE REVIEW

**Comment by williamcroberts** [comment]
@idesai you need to review + test this and submit this back with a testing script...

**Comment by williamcroberts** [comment]
You need to submit a test_tpm2_dictionarylockout.sh and add it to test_all.sh
I should have forced this for createpolicy.... so if you want this merged also submit in a separate commit a test script for createpolicy

**Comment by williamcroberts** [comment]
Actually it appears the build wen't down with your PR: https://travis-ci.org/01org/tpm2.0-tools/builds/207440409

So I am reverting that here: https://github.com/01org/tpm2.0-tools/pull/248

Please re-upload and submit with test

**Comment by idesai** [comment]
This PR somehow has code for both create policy and dictionarylockout.
I have created a separate PR for create policy and dictionarylockout and also added the unit tests for them. 
So may be drop this PR and lets review the segregated PRs for the two. Thanks and sorry for the confusion.

**Pull request closed without merging**
