### PR TITLE
tpm2_getpubek: port to use common infrastructure

### PR DESCRIPTION
**Pull request by williamcroberts**
Refactor to be inline with coding standard.

Signed-off-by: William Roberts <william.c.roberts@intel.com>

### CODE REVIEW

**Comment by flihp** [comment]
I dropped @idesai from the reviewer list. Making the executive decision that 1 review is sufficient.

**Comment by williamcroberts** [comment]
Does the tool require you to wait for all reviewers to review?

**Comment by flihp** [comment]
I don't think so. It may if you use the 'merge' button but the merge commits drive me nuts when looking at git history directly so I manually merge (--ff-only). I just removed the extra reviewer ... because it seemed like the right thing to do? Probably wasn't necessary though :man_shrugging:

**Comment by williamcroberts** [comment]
@flihp they have the ability to "rebase and merge" on the "merge pull request" button if you use the drop down selection on the right hand side of that button. So we should just be using that.

**Pull request merged**
