### PR TITLE
tpm2_listpcrs: use dymaic tcti/sapi

### PR DESCRIPTION
**Pull request by williamcroberts**
Port to use execute_tool() interface and do some minor
internal refactoring.

Signed-off-by: William Roberts <william.c.roberts@intel.com>

### CODE REVIEW

**Comment by flihp** [comment]
I've added a section with steps to ensure dependencies on `common.c` are removed: https://github.com/01org/tpm2.0-tools/wiki/tool-porting-guide#build-without-the-socket-tcti

**Comment by flihp** [comment]
ROFL I just made the same mistake in one of mine. Didn't find it till after I merged it. Doh!

**Comment by williamcroberts** [comment]
@flihp changes to common made

**Comment by flihp** [comment]
Merged in 1f0e51d41a48479fc1febdfb1fe5c3edbba8ca79 and 828f0d6e851bbbec09a5ebfd964a3ad3a995f308

**Pull request closed without merging**
