### PR TITLE
Issue 261 211

### PR DESCRIPTION
**Pull request by williamcroberts**

### CODE REVIEW

**Comment by williamcroberts** [comment]
Interesting, on this version of man we get:

```
man/man8/tpm2_getpubek.8:36: warning [p 1, 1.7i]: cannot adjust line
man/man8/tpm2_getpubek.8:44: warning [p 1, 3.1i]: cannot adjust line
man/man8/tpm2_getpubek.8:51: warning [p 1, 4.2i]: cannot adjust line
```

**Comment by flihp** [comment]
This is great. Is the travis CI failure caused by the new check?

**Comment by williamcroberts** [comment]
@flihp  yes

**Comment by williamcroberts** [comment]
Don't know how to fix the warnings, abandoning.

**Pull request closed without merging**
